---
# tasks file for db
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!! internal ip {{ ansible_all_ipv4_addresses }} external ip {{ ansible_ssh_host }}"

- name: Change mongo config file
  template:
     src: mongod.conf.j2
     dest: /etc/mongod.conf
     mode: 420
  notify: restart mongod
