- name: Fetch the latest version of application code
  hosts: app
  become: true
  tags: deploy-tag
  tasks:
    - name: download app
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/{{ deploy_user }}/reddit
        version: monolith
    - name: Bundle install
      bundler:
        state: present
        chdir: /home/{{ deploy_user }}/reddit
      notify: reload puma

  handlers:
    - name: reload puma
      become: true
      systemd: name=puma state=restarted
