- name: Configure hosts to application
  hosts: all
  become: true
  tasks:
    - name: Install ruby
      apt:
        pkg:
        - ruby-full
        - ruby-bundler
        - build-essential
        state: present
        update_cache: yes
