Vagrant.configure("2") do |config|

  config.vm.boot_timeout = 1600
  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "dbserver" do |db|
    db.vm.box = "ubuntu/trusty64"
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "10.111.10.10"
  end

end
